<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>BitShelter.Service</AssemblyName>
    <RootNamespace>BitShelter.Service</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\BitShelter.Common\BitShelter.Common.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.ServiceProcess.ServiceController" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="BitShelter.Tests" />
  </ItemGroup>
</Project>
