<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>BitShelter.Benchmark</RootNamespace>
    <AssemblyName>BitShelter.Benchmark</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\BitShelter.Common\BitShelter.Common.csproj" />
  </ItemGroup>
</Project>
