<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>BitShelter.Benchmark.Console</RootNamespace>
    <AssemblyName>BitShelter.Benchmark.Console</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\BitShelter.Benchmark\BitShelter.Benchmark.csproj" />
  </ItemGroup>
</Project>
