<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyName>BitShelter.Agent</AssemblyName>
    <RootNamespace>BitShelter.Agent</RootNamespace>
    <GenerateResourceUsePreserializedResources>true</GenerateResourceUsePreserializedResources>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>BitShelter.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\BitShelter.Common\BitShelter.Common.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CronExpressionDescriptor" />
    <PackageReference Include="EWSoftware.ListControls" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="BitShelter.ico" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="BitShelter.Tests" />
  </ItemGroup>
</Project>
